#
# Our FileBeat configuration to deploy local JSON logs to Elastic Search
#

filebeat.inputs:

- type: log

  # Enable log shipping
  enabled: true

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    # My log file locations when running on Mac OS
    - /Users/gary/projects/authguidance.apisample.nodejs/logs/*.log
    - /Users/gary/projects/authguidance.apisample.netcore/logs/*.log
    - /Users/gary/projects/authguidance.apisample.javaspringboot/logs/*.log

    # My log file locations when running on Windows
    # - C:\DEV\authguidance.apisample.nodejs\logs\*.log
    # - C:\DEV\authguidance.apisample.netcore\logs\*.log
    # - C:\DEV\authguidance.apisample.javaspringboot\logs\*.log

    # My log file locations when running on Linux
    # - /home/gary/projects/authguidance.apisample.nodejs/logs/*.log
    # - /home/gary/projects/authguidance.apisample.netcore/logs/*.log
    # - /home/gary/projects/authguidance.apisample.javaspringboot/logs/*.log

  json:
    keys_under_root: true
    overwrite_keys: true
    add_error_key: false

#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 1

#================================ General =====================================

# Disable index lifecycle management
setup.ilm.enabled: false

# Set these to reference our API logs index
setup.template.name: apilogs
setup.template.pattern: apilogs-*

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]

  # Reference our Elastic Search index
  index: apilogs

  # The ingestion pipeline manages finalising Elastic Search data
  pipelines:
    - pipeline: apilogs-filebeat-ingest-pipeline

# Configure processors to enhance or manipulate events generated by the beat.
processors:
  # Do not add filebeat fields to Elastic Search
  - drop_fields:
      fields: ["agent", "ecs", "host", "input", "log", "version"]
